services:
  backend:
    image: gobarihimanshu071/churn-api:latest
    container_name: churn-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: gobarihimanshu071/churn-frontend:latest
    container_name: churn-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped